#!/usr/bin/env bun
/**
 * Every action a user can take, listed from the code, so a review walks all of
 * them instead of sampling hotspots.
 *
 * Usage:
 *   bun inventory.ts --sql <schema.sql> --src <dir> [--src <dir> ...] --out <job>/00-inventory.md
 *
 * One row per server function in the `public` schema (what a client can call),
 * plus one row per client hook that writes a table directly. Each row names
 * the hooks that call it and the files that use those hooks, found by text
 * search, so the list is the same every run. Rows already present in --out
 * keep their verdict, prior art and findings; new rows are appended blank.
 *
 * @remarks Grouping rows into features is left to the reviewer: the list
 * guarantees nothing is skipped, not how it is read.
 */
import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';

const args = process.argv.slice(2);
const opt = (k: string) => args.flatMap((a, i) => (a === k ? [args[i + 1]] : []));
const sql = opt('--sql')[0];
const srcs = opt('--src');
const out = opt('--out')[0];
if (!sql || srcs.length === 0 || !out) {
  console.error('usage: inventory.ts --sql <schema.sql> --src <dir>... --out <file>');
  process.exit(2);
}
const root = process.cwd();
const SKIP = new Set(['node_modules', 'dist', '.turbo', 'build', '.git']);

function files(dir: string, acc: string[] = []): string[] {
  for (const e of readdirSync(dir)) {
    if (SKIP.has(e)) continue;
    const f = join(dir, e);
    if (statSync(f).isDirectory()) files(f, acc);
    else if (/\.(tsx?|jsx?)$/.test(e) && !/\.(test|spec|d)\.[tj]sx?$/.test(e)) acc.push(f);
  }
  return acc;
}

const schema = readFileSync(sql, 'utf8');
const rpcs = [
  ...new Set(
    [...schema.matchAll(/CREATE (?:OR REPLACE )?FUNCTION "public"\."([a-z0-9_]+)"\(/gi)].map((m) => m[1]),
  ),
].sort();

const src = srcs.flatMap((d) => files(d)).map((f) => ({ f: relative(root, f), text: readFileSync(f, 'utf8') }));

/** exported hooks per file, with the text of each hook's body */
type Hook = { name: string; file: string; body: string };
const hooks: Hook[] = [];
for (const { f, text } of src) {
  const starts = [...text.matchAll(/export (?:async )?function (use[A-Z]\w*)\s*\(/g)];
  starts.forEach((m, i) => {
    const end = i + 1 < starts.length ? starts[i + 1].index! : text.length;
    hooks.push({ name: m[1], file: f, body: text.slice(m.index!, end) });
  });
}

const usersOf = (name: string) =>
  src.filter(({ text }) => new RegExp(`\\b${name}\\b`).test(text)).map(({ f }) => f);

type Row = { id: string; kind: string; target: string; hooks: string[]; screens: string[] };
const rows: Row[] = [];
for (const r of rpcs) {
  const callers = hooks.filter((h) => new RegExp(`rpc\\(\\s*['"\`]${r}['"\`]`).test(h.body));
  const direct = src.filter(({ text }) => new RegExp(`rpc\\(\\s*['"\`]${r}['"\`]`).test(text)).map(({ f }) => f);
  rows.push({
    id: `rpc:${r}`,
    kind: 'server function',
    target: r,
    hooks: callers.map((h) => `${h.name} (${h.file})`),
    screens: [...new Set([...callers.flatMap((h) => usersOf(h.name)), ...direct])].sort(),
  });
}
for (const h of hooks) {
  const writes = [...h.body.matchAll(/from\(\s*['"`]([a-z0-9_]+)['"`]\s*\)[\s\S]{0,200}?\.(insert|update|upsert|delete)\(/g)];
  for (const t of new Set(writes.map((w) => `${w[1]}.${w[2]}`))) {
    rows.push({
      id: `write:${h.name}:${t}`,
      kind: 'client write',
      target: t,
      hooks: [`${h.name} (${h.file})`],
      screens: usersOf(h.name).filter((f) => f !== h.file).sort(),
    });
  }
}

/* KEEP WHAT A REVIEWER ALREADY WROTE: verdict, prior art and findings survive a rerun */
const kept = new Map<string, string[]>();
if (existsSync(out)) {
  for (const line of readFileSync(out, 'utf8').split('\n')) {
    const cells = line.split('|').map((c) => c.trim());
    if (cells.length > 7 && cells[1]?.startsWith('`')) kept.set(cells[1].replace(/`/g, ''), cells.slice(5, 8));
  }
}

const esc = (s: string) => s.replace(/\|/g, '\\|');
const lines = [
  '# Inventory: every action, walked once',
  '',
  `Generated by inventory.ts from ${relative(root, sql)} and ${srcs.map((s) => relative(root, s) || '.').join(', ')}. ${rows.length} rows.`,
  'Every row gets a verdict (keep, refactor, defect, dead), a prior-art path or `n/a: <why>`, and its findings. `board.ts` fails while one is blank.',
  '',
  '| Id | Kind | Called by | Used on | Verdict | Prior art | Findings |',
  '|---|---|---|---|---|---|---|',
  ...rows.map((r) => {
    const [v = '', p = '', f = ''] = kept.get(r.id) ?? [];
    return `| \`${r.id}\` | ${r.kind} | ${esc(r.hooks.join('<br>')) || '(none found)'} | ${esc(r.screens.join('<br>')) || '(none found)'} | ${v} | ${p} | ${f} |`;
  }),
  '',
];
writeFileSync(out, lines.join('\n'));
const blank = rows.filter((r) => !(kept.get(r.id)?.[0])).length;
console.log(`inventory: ${rows.length} rows (${rpcs.length} server functions, ${rows.length - rpcs.length} client writes), ${blank} not yet walked → ${out}`);
